# JONATHAN PATRICK CHEN
# JONATPC2@UCI.EDU
# 80752008

'''
Temp docstring
'''

# HEADERS
TITLE_PROFILE = 'Profiles'
HEADER_ACCESS_PROFILE = 'Access Profiles'
HEADER_DELETE_PROFILE = 'Delete Profiles'
BUTTON_ADMIN = 'Toggle Debug'
BUTTON_EDIT_LOGIN = 'Modify Login'

WINDOW_MAIN = 'DSU Client'
WINDOW_PROFILE = 'DSU Profile'
WINDOW_MSG = 'DSU Messenger'

# MANAGE PROFILE
BUTTON_CREATE_PROFILE = 'Create Profile'
BUTTON_ACCESS_PROFILE = 'Access'
BUTTON_DELETE_PROFILE = 'Delete'

# CREATE PROFILE
POPUP_HEADER_CREATE_PROFILE = 'Create a profile'
POPUP_PROMPT_GET_NAME = 'Enter a username'
POPUP_PROMPT_GET_NAME_BLANK = 'Username cannot be empty'
POPUP_PROMPT_GET_NAME_DUPLICATE = "Username already used"
POPUP_PROMPT_GET_PW = 'Enter a password'
POPUP_PROMPT_GET_PW_BLANK = 'Password cannot be empty'

# BIO
BUTTON_EDIT_BIO = 'Edit bio'
BUTTON_PUBLISH_BIO = 'Publish bio'
BUTTON_PUBLISH_BIO_UNJOINED = 'Join server'

POPUP_HEADER_EDIT_BIO = 'Edit bio'
POPUP_PROMPT_GET_BIO = 'Describe yourself here!'
POPUP_PROMPT_GET_BIO_BLANK = 'Bio cannot be empty!'

# GET SERVER
POPUP_HEADER_SERVER = 'Select server'
POPUP_PROMPT_GET_IP = 'Enter the server IP address. Default 168.235.86.101'
POPUP_PROMPT_GET_IP_BLANK = 'IP address cannot be blank!'
POPUP_PROMPT_GET_PORT = 'Enter the server port. Default 3021'
POPUP_PROMPT_GET_PORT_BLANK = 'Port cannot be blank!'

# USER POST
BUTTON_CREATE_POST = 'Create Post'
BUTTON_EDIT_POST = 'Edit'
BUTTON_PUBLISH_POST = 'Publish'
BUTTON_DELETE_POST = 'Delete'

POPUP_HEADER_CREATE_POST = 'Create a post'
POPUP_PROMPT_GET_CONTENT = 'Write your thoughts here!'
POPUP_PROMPT_GET_CONTENT_BLANK = 'Cannot make an empty post!'

# EDIT POST
POPUP_HEADER_EDIT_POST = 'Edit this post'
POPUP_PROMPT_GET_EDIT = 'Previous post:\n'
POPUP_PROMPT_GET_EDIT_BLANK = POPUP_PROMPT_GET_CONTENT_BLANK

# ADD FRIEND
POPUP_HEADER_EDIT_POST = 'Edit this post'
POPUP_PROMPT_GET_EDIT = 'Previous post:\n'
POPUP_PROMPT_GET_EDIT_BLANK = POPUP_PROMPT_GET_CONTENT_BLANK
